In [1]:
import pandas as pd

url = "https://raw.githubusercontent.com/Ghhaidaa/Data-Mining-Project-/refs/heads/main/Dataset/Raw_dataset.csv"
df = pd.read_csv(url)

In [ ]:
df.shape

(1000, 12)

In [ ]:
df.dtypes

student_id                      int64
gender                         object
study_time_hours              float64
attendance_percent            float64
sleep_hours                   float64
parental_education             object
internet_access                object
extracurricular_activities     object
part_time_job                  object
previous_grade                float64
final_exam_score              float64
final_grade                    object
dtype: object

# **Project Goal**

The goal of this project is to analyze student performance and study habits using data mining techniques.

For classification, the project aims to classify students into different performance categories based on their academic characteristics and study habits.

For clustering , the project aims to group students with similar academic characteristics and study habits to discover meaningful patterns in the dataset.

## Dataset Source

The dataset used in this project is the Student Performance and Study Habits Dataset, obtained from Kaggle.

Dataset URL: https://www.kaggle.com/datasets/harshadapatil31/student-performance-and-study-habits-dataset

## Dataset Description

The dataset contains 1000 instances (rows) and 12 attributes (columns). The following code displays the number of instances and attributes in the dataset.

In [ ]:
df.shape

(1000, 12)

### Data Types

The following code displays the data type of each attribute in the dataset.

In [ ]:
df.dtypes

student_id                      int64
gender                         object
study_time_hours              float64
attendance_percent            float64
sleep_hours                   float64
parental_education             object
internet_access                object
extracurricular_activities     object
part_time_job                  object
previous_grade                float64
final_exam_score              float64
final_grade                    object
dtype: object

The dataset contains numerical and categorical attributes. The numerical attributes are represented by int64 and float64 data types, while the categorical attributes are represented by the object data type.

### class & Dataset Exploration
 The class attribute is 'final_grade', which represents the final grade of each student

In [3]:
print("Class values")
print(df['final_grade'].unique())

Class values
['A' 'B' 'D' 'C' 'F']

In [5]:
print ("Number of classes:", df['final_grade'].nunique())

print("Number of instances in each class:")
print(df['final_grade'].value_counts())

Number of classes: 5
Number of instances in each class:
final_grade
B    354
A    284
C    261
D     89
F     12
Name: count, dtype: int64

In [6]:
print("Sample of the Raw Dataset:")
df.head()

Sample of the Raw Dataset:

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade
0,1,Male,4.0,98.0,6.5,Bachelors,Yes,Yes,No,76.9,100.0,A
1,2,Female,6.3,100.0,5.7,High School,Yes,Yes,Yes,75.5,100.0,A
2,3,Male,4.9,85.3,7.9,Bachelors,Yes,No,Yes,88.5,97.3,A
3,4,Male,2.6,77.5,8.0,NaN,Yes,Yes,No,85.1,83.8,B
4,5,Male,2.2,89.6,4.6,Bachelors,Yes,No,Yes,61.8,68.3,D